### ISSUE TITLE
Error running `make` on Mac OSX El Capitan

### ISSUE THREAD

**Issue by ch3nkula** [Ch3ck/ytd#3]
Trying to build the application gives the error;
`
building cmd/ytd
ytd.go:26:2: cannot find package "github.com/Ch3ck/ytd/api" in any of:
        /Users/alangiderick/go/src/ytd/vendor/github.com/Ch3ck/ytd/api (vendor tree)
        /usr/local/opt/go/libexec/src/github.com/Ch3ck/ytd/api (from $GOROOT)
        /Users/alangiderick/go/src/github.com/Ch3ck/ytd/api (from $GOPATH)
ytd.go:25:2: cannot find package "github.com/Ch3ck/ytd/auth" in any of:
        /Users/alangiderick/go/src/ytd/vendor/github.com/Ch3ck/ytd/auth (vendor tree)
        /usr/local/opt/go/libexec/src/github.com/Ch3ck/ytd/auth (from $GOROOT)
        /Users/alangiderick/go/src/github.com/Ch3ck/ytd/auth (from $GOPATH)
ytd.go:19:2: cannot find package "os/strings" in any of:
        /Users/alangiderick/go/src/ytd/vendor/os/strings (vendor tree)
        /usr/local/opt/go/libexec/src/os/strings (from $GOROOT)
        /Users/alangiderick/go/src/os/strings (from $GOPATH)
ytd
./simple.go:99: missing '
./simple.go:99: syntax error: unexpected literal '%, expecting comma or )
make: *** [build] Error 2
`

**Comment by ch3nkula** [comment]
Closing the issue since this is still an experimentation. But will reopen if need be.

**Comment by ch3nkula** [comment]
This error is due to the `logrus` package that is not available. Checking this out.

**Comment by Ch3ck** [comment]
@ch3nkula  Have you checked if your $GOPATH is set properly?

**Comment by ch3nkula** [comment]
This has been resolved after working a little bit. Check PR #7.
